server:
  port: 9090
spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://62.109.21.174/users
    username: users
    password: users
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always

  config:
    activate:
      on-profile: ci,test
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:users
      username: users
      password: users